### ISSUE TITLE
Header & "divider bar" disappeared after MM upgrade to 2.7.1

### ISSUE THREAD

**Issue by upupdown42** [ryck/MMM-AQI#1]
Hi,
after reinstalling my magicmirror with the latest one (2.7.1), the header line including this small bar disappeared. I didnt change the code or something. Any ideas how to fix it? Thanks!

**Comment by upupdown42** [comment]
Found a solution:
In MMM-AQI.js replace

```
getHeader: function() {
    return this.config.header;
  },
```
with

```
getHeader: function() {
    return this.data.header;
  },
```

Maybe the author can add this to his original version (don't know how to pull a request).
Cheers

**Comment by ryck** [comment]
I just pushed a fix for this.
Sorry for the delay, and thanks to upupdown42 for reporting the issue and propose a solution!

PS: Doing a pull request is really easy, let me know if you want me to show you how
