### ISSUE TITLE
Could you change the unit of AQI?

### ISSUE THREAD

**Issue by yoonsoln** [ryck/MMM-AQI#2]
I added your module on the 3rd Party Modules list.
(https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules)

By the way, could you change the unit of AQI?
I want to change PM25 to PM2.5. (Please refer the capture below.)
![Capture](https://user-images.githubusercontent.com/43337517/65381989-575a8280-dd37-11e9-9941-3f86c7cbd831.PNG)

Here's a example (another module)
![MMM-aqicn](https://user-images.githubusercontent.com/43337517/65382020-c7690880-dd37-11e9-84ef-5cfe92e0dc43.PNG)
https://github.com/gpailler/MMM-aqicn

Thank you! (I'm using your module in our school's MagicMirror!)

**Comment by ryck** [comment]
Hi @yoonsoln 

Thanks fro adding it to the list!

Right now, those values come directly from the API (ie, that's the original name). I do that so in case they add more data it will show directly in the module...

But maybe I will implement a shorter display mode (like the one in your screenshot) one day...
